sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t hagbardc3line/travis -f Dockerfile.dev .

script:
  - docker run -e CI=true hagbardc3line/travis npm run test